//
//  GradientView.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import "Gradient.h"

@interface GradientView : UIView {
    Gradient *gradient;
}

@property (nonatomic, retain) Gradient *gradient;

@end
