//
//  Gradient.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <Foundation/Foundation.h>
#import "GradientNode.h"

@interface Gradient : NSObject {
    NSNumber *angle;
    NSMutableArray *nodes;
}

@property (nonatomic, copy) NSNumber *angle;
@property (nonatomic, retain) NSMutableArray *nodes;

- (void)addNode:(GradientNode *)node;
- (void)removeNode:(GradientNode *)node;


@end
