//
//  Gradient.m
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import "Gradient.h"

#define ENCODE_ANGLE    @"angle"
#define ENCODE_NODES    @"nodes"

@implementation Gradient
@synthesize angle;
@synthesize nodes;

- (id)init {
    self = [super init];
    if (self) {
        self.nodes = [NSMutableArray array];
        
        // ------------------------------------------------
        // Pre-setup
        // ------------------------------------------------
        self.angle = [NSNumber numberWithFloat:90.0];
    }
    return self;
}

- (void)dealloc {
    self.angle = nil;
    self.nodes = nil;
    [super dealloc];
}

- (void)sort {
    NSArray *descriptors = [NSArray arrayWithObject:[NSSortDescriptor sortDescriptorWithKey:@"location" ascending:YES]];
    [self.nodes sortUsingDescriptors:descriptors];
}

- (void)addNode:(GradientNode *)node {
    [self.nodes addObject:node];
    [self sort];
}

- (void)removeNode:(GradientNode *)node {
    [self.nodes removeObject:node];
    [self sort];
}

@end
