//
//  SettingsViewController.h
//  Interface 
//
//  Generated by Interface 2
//  http://lesscode.co.nz/interface
//

#import <UIKit/UIKit.h>
#import <QuartzCore/QuartzCore.h>

@interface SettingsViewController : UIViewController {
  
}

@property (nonatomic, retain) NSMutableArray *tableView1Data;

@end